server.port=8080

spring.datasource.url=jdbc:postgresql://ep-wispy-hill-aggrsj0s-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_sBVZr8co1Pbx

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.admin.username=admin
app.admin.email=admin@01blog.local
app.admin.password=admin@123456

app.jwt.secret=dGhpcy1pcy1hLXNlY3VyZS1zZWNyZXQta2V5LWZvci1qd3Q=
app.jwt.expiration=86400000